; PlatformIO 核心配置文件 (主从机通用)

[env:esp32-s3-n8r2]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino, espidf

; 串口监视器波特率
monitor_speed = 115200
upload_port = COM5    ; 从机改为 COM5
monitor_port = COM5   ; 从机改为 COM5


; --- 硬件与分区配置 ---
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.arduino.memory_type = qspi_qspi ; 开启高速 Flash 和 PSRAM 映射

; --- 编译与优化参数 ---
build_flags = 
    -D BOARD_HAS_PSRAM
    -D CORE_DEBUG_LEVEL=3           ; 允许输出普通 Log，但严禁在中断里打印！
    
    ; 【算力压榨ces
    -O3                             ; 开启 C/C++ 最高级别性能优化
    -ffast-math                     ; 开启极速浮点数学运算 (加速 FOC 的三角函数)
    -Wno-error=double-promotion     ; 屏蔽 FOC 库中的浮点精度转换警告
    -Wno-maybe-uninitialized        ; 屏蔽未初始化变量警告 (保持控制台干净)