; PlatformIO 从机固件构建配置
;
; bring-up 开关集中在 config/build 和 config/core。
; 需要临时切换硬件/运行模式时，通过 build_flags 增加 -D SLAVE_*=...。

[platformio]
default_envs = slave

[env:slave]
platform = espressif32
board = rymcu-esp32-s3-devkitc-1
framework = arduino, espidf

monitor_speed = 115200
upload_port = COM10
monitor_port = COM10

board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

build_unflags =
    -DBOARD_HAS_PSRAM

build_flags =
    -D APP_ROLE_SLAVE=1
    -D CORE_DEBUG_LEVEL=3
    -O3
    -ffast-math
    -Wno-error=double-promotion
    -Wno-maybe-uninitialized
