#pragma once

#include <stdint.h>

#include "slave/config/build/slave_build_options.h"

// 从机控制周期与热路径分频配置。
// SingleX、SingleY、DualXY 均按 4kHz / 250us 设计；DryRun 保持 500us。

#ifndef SLAVE_CONTROL_LOOP_PERIOD_US_CONFIG
#if SLAVE_RUN_MODE == SLAVE_MODE_SINGLE_X_4KHZ_ID || \
    SLAVE_RUN_MODE == SLAVE_MODE_SINGLE_Y_4KHZ_ID || \
    SLAVE_RUN_MODE == SLAVE_MODE_DUAL_XY_4KHZ_ID
#define SLAVE_CONTROL_LOOP_PERIOD_US_CONFIG 250UL
#else
#define SLAVE_CONTROL_LOOP_PERIOD_US_CONFIG 500UL
#endif
#endif

static constexpr uint32_t SLAVE_CONTROL_LOOP_PERIOD_US =
    SLAVE_CONTROL_LOOP_PERIOD_US_CONFIG;
static constexpr uint32_t CONTROL_LOOP_PERIOD_US =
    SLAVE_CONTROL_LOOP_PERIOD_US;

#ifndef SLAVE_FAST_PLANNER_ENABLED
#if SLAVE_RUN_MODE == SLAVE_MODE_DUAL_XY_4KHZ_ID
#define SLAVE_FAST_PLANNER_ENABLED 0
#else
#define SLAVE_FAST_PLANNER_ENABLED 1
#endif
#endif

#ifndef SLAVE_PLANNER_EVERY_N_STEPS
#if SLAVE_FAST_PLANNER_ENABLED
#define SLAVE_PLANNER_EVERY_N_STEPS 1UL
#else
#define SLAVE_PLANNER_EVERY_N_STEPS 2UL
#endif
#endif

#ifndef SLAVE_RUNTIME_PUBLISH_EVERY_N_STEPS
#define SLAVE_RUNTIME_PUBLISH_EVERY_N_STEPS 4UL
#endif

#ifndef SLAVE_MOTION_SNAPSHOT_EVERY_N_STEPS
#define SLAVE_MOTION_SNAPSHOT_EVERY_N_STEPS 4UL
#endif

#ifndef SLAVE_X_FOC_EVERY_N_STEPS
#define SLAVE_X_FOC_EVERY_N_STEPS 1UL
#endif

#ifndef SLAVE_X_MOVE_EVERY_N_STEPS
#define SLAVE_X_MOVE_EVERY_N_STEPS 1UL
#endif

#ifndef SLAVE_Y_FOC_EVERY_N_STEPS
#define SLAVE_Y_FOC_EVERY_N_STEPS 1UL
#endif

#ifndef SLAVE_Y_MOVE_EVERY_N_STEPS
#define SLAVE_Y_MOVE_EVERY_N_STEPS 1UL
#endif
